In [2]:
from pop import AI
perc = AI.Perceptron(input_size=3)

In [3]:
import numpy as np

a1 = [173, 171, 162, 187, 157, 169, 177, 159, 182]
a2 = [270, 275, 245, 280, 230, 265, 270, 250, 275]
a3 = [17, 51, 62, 12, 47, 30, 5, 32, 0]
a4 = [0, 1, 1, 0, 1, 0, 0, 1, 0]

perc.X_data = np.array([a1,a2,a3], dtype=np.float32).T
perc.Y_data = np.array(a4, dtype=np.float32).reshape(-1,1)

In [4]:
perc.train()

10 step loss: 28.78866958618164
20 step loss: 8.29165267944336
30 step loss: 8.09310245513916
40 step loss: 4.649871826171875
50 step loss: 2.7671220302581787
60 step loss: 1.506102204322815
70 step loss: 0.6392616629600525
80 step loss: 0.4116511940956116
90 step loss: 0.26499423384666443
100 step loss: 0.21939757466316223
Training is done.
Time spent: 4.0 s
Training speed: 24.9 step/s


In [6]:
perc.run()

run with :  [[173. 270.  17.]
 [171. 275.  51.]
 [162. 245.  62.]
 [187. 280.  12.]
 [157. 230.  47.]
 [169. 265.  30.]
 [177. 270.   5.]
 [159. 250.  32.]
 [182. 275.   0.]]


array([[0.05948913],
       [0.7007809 ],
       [0.9983718 ],
       [0.20181987],
       [0.99704176],
       [0.29729408],
       [0.03249643],
       [0.41271737],
       [0.02362378]], dtype=float32)

In [9]:
perc.train(times=1000, print_every=100)

200 step loss: 0.13007815182209015
300 step loss: 0.11308569461107254
400 step loss: 0.10386130213737488
500 step loss: 0.09719523042440414
600 step loss: 0.09164721518754959
700 step loss: 0.08666393160820007
800 step loss: 0.08199917525053024
900 step loss: 0.07753903418779373
1000 step loss: 0.07323416322469711
1100 step loss: 0.06906897574663162
Training is done.
Time spent: 8.5 s
Training speed: 117.3 step/s


In [10]:
pred = perc.run()
print(pred)
pred_label = (pred >= 0.5).astype(np.float32)
accuracy = np.mean(pred_label.reshape(-1,1) == perc.Y_data)
print(accuracy)

run with :  [[173. 270.  17.]
 [171. 275.  51.]
 [162. 245.  62.]
 [187. 280.  12.]
 [157. 230.  47.]
 [169. 265.  30.]
 [177. 270.   5.]
 [159. 250.  32.]
 [182. 275.   0.]]
[[2.2396963e-04]
 [9.9984241e-01]
 [1.0000000e+00]
 [5.6395871e-05]
 [9.9999881e-01]
 [2.5964126e-01]
 [8.4276815e-07]
 [7.2600931e-01]
 [6.0793219e-08]]
1.0
