In [1]:
from pop import AI
ann = AI.ANN(input_size=3, output_size=3)

In [2]:
import numpy as np

a1 = [73, 62, 83, 110, 139, 123, 177, 159, 182]   # 키
a2 = [90, 70, 100, 150, 220, 190, 275, 240, 280]  # 신발사이즈
a3 = [1, 0, 2, 7, 15, 10, 7, 35, 15]              # 머리카락 길이
a4 = [[1,0,0],[1,0,0],[1,0,0],[0,1,0],[0,1,0],[0,1,0],[0,0,1],[0,0,1],[0,0,1]]  # 유아 어린이 성인

ann.X_data = np.array([a1,a2,a3], dtype=np.float32).T
ann.Y_data = np.array(a4, dtype=np.float32)

In [3]:
ann.train()

10 step loss: 13.383576393127441
20 step loss: 8.611888885498047
30 step loss: 4.181770324707031
40 step loss: 2.708383321762085
50 step loss: 1.6005107164382935
60 step loss: 0.8219422101974487
70 step loss: 0.6751601696014404
80 step loss: 0.5941054821014404
90 step loss: 0.5628328323364258
100 step loss: 0.5374138355255127
Training is done.
Time spent: 5.3 s
Training speed: 19.0 step/s


In [ ]:
ann.run()

In [4]:
result = ann.run()
pred_index = np.argmax(result, axis=1)
true_index = np.argmax(ann.Y_data, axis=1)
classes = ["유아", "어린이", "성인"]
accuracy = np.mean(pred_index == true_index)
print(f"정확도는 : {accuracy}")

run with :  [[ 73.  90.   1.]
 [ 62.  70.   0.]
 [ 83. 100.   2.]
 [110. 150.   7.]
 [139. 220.  15.]
 [123. 190.  10.]
 [177. 275.   7.]
 [159. 240.  35.]
 [182. 280.  15.]]
정확도는 : 0.7777777777777778


In [ ]:
ann.train(times=1000, print_every=100)

In [ ]:
result = ann.run()
pred_index = np.argmax(result, axis=1)
true_index = np.argmax(ann.Y_data, axis=1)
classes = ["유아", "어린이", "성인"]
accuracy = np.mean(pred_index == true_index)
print(f"정확도는 : {accuracy}")

In [ ]:
for i in range(len(pred_index)):
    print(f"{i} 번 데이터: :","입력 = ", ann.X_data[i], "/ 예측 = ", classes[pred_index[i]])
    print("/ 정답 =", classes[true_index[i]])

In [7]:
# confusion matrix
num_classes = len(classes)
confusion = np.zeros((num_classes, num_classes), dtype=np.int32)

for t, p in zip(true_index, pred_index):
    confusion[t, p] += 1

for name in classes:
    print(f"{name:>6}", end="")
print()

for i, name in enumerate(classes):
    print(f"{name:>6}", end="")
    for j in range(num_classes):
        print(f"{confusion[i,j]:>6}", end="")
    print()


    유아   어린이    성인
    유아     3     0     0
   어린이     0     1     2
    성인     0     0     3
