In [2]:
import numpy as np

x =  np.arange(4).reshape(2,2) #Numpy의 ndarray을 0 부터 3까지로 채워 생성하고 2,2 형태로 변형
print(x)
y =  np.arange(3,-1,-1).reshape(2,2) #Numpy의 ndarray을 3 부터 0까지로 채워 생성하고 2,2 형태로 변형
print(y)

s1 =  np.where(x > y, x, y) #ndarray x 와 y를 차례로 비교해 x의 원소가 크면 x, y의 원소가 크면 y 원소를 반환
print(s1)

[[0 1]
 [2 3]]
[[3 2]
 [1 0]]
[[3 2]
 [2 3]]
